version: '2'
services:
  data:
    image: busybox
    container_name: sample-ec-app-data
    volumes:
      - bundle:/usr/local/bundle
      - mysql-data:/var/lib/mysql
      - redis-data:/data

  app: &base
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: docker/.env
    container_name: sample-ec-app
    volumes:
      - .:/app
    volumes_from:
      - data
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'

  db:
    image: mysql:5.7.23
    env_file: docker/.env
    container_name: sample-ec-mysql
    volumes_from:
      - data
    volumes:
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

  redis:
    image: redis:3.2.9-alpine
    env_file: docker/.env
    container_name: sample-ec-redis
    volumes_from:
      - data
    ports:
      - 6379:6379

volumes:
  bundle:
    driver: local
  mysql-data:
    driver: local
  redis-data:
    driver: local
